In [1]:
import pandas as pd


In [2]:
data = {
    'name':['sudh','krish','hitesh','tuleshko'],
    'salary':[100,200,300,400],
    'mail_id' : ['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tuleshko@ineuron.ai'],
    'addr':['blr','blr','blr','mum']
}

In [3]:
pd.DataFrame(data, index=['a','b','c','d']) 

name  salary              mail_id addr
a      sudh     100      sudh@ineuron.ai  blr
b     krish     200     krish@ineuron.ai  blr
c    hitesh     300    hitesh@ineuron.ai  blr
d  tuleshko     400  tuleshko@ineuron.ai  mum

In [4]:
pd.DataFrame(data,columns=[0,1,2,3])

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [5]:
df = pd.DataFrame(data)

In [6]:
df

name  salary              mail_id addr
0      sudh     100      sudh@ineuron.ai  blr
1     krish     200     krish@ineuron.ai  blr
2    hitesh     300    hitesh@ineuron.ai  blr
3  tuleshko     400  tuleshko@ineuron.ai  mum

In [7]:
df.loc[0:3]  # it is depend on own index

name  salary              mail_id addr
0      sudh     100      sudh@ineuron.ai  blr
1     krish     200     krish@ineuron.ai  blr
2    hitesh     300    hitesh@ineuron.ai  blr
3  tuleshko     400  tuleshko@ineuron.ai  mum

In [8]:
df.iloc[0:2,0:3] # it is work on defoult indexes

name  salary           mail_id
0   sudh     100   sudh@ineuron.ai
1  krish     200  krish@ineuron.ai

In [13]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [15]:
df1 = pd.DataFrame(data1)

In [16]:
pd.concat([df,df1])

name  salary              mail_id addr    pf_nu  income_tax  mobile_no  \
0      sudh   100.0      sudh@ineuron.ai  blr      NaN         NaN        NaN   
1     krish   200.0     krish@ineuron.ai  blr      NaN         NaN        NaN   
2    hitesh   300.0    hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tuleshko   400.0  tuleshko@ineuron.ai  mum      NaN         NaN        NaN   
0       NaN     NaN                  NaN  NaN    234.0       234.0    23543.0   
1       NaN     NaN                  NaN  NaN     45.0       565.0    43543.0   
2       NaN     NaN                  NaN  NaN  54465.0       767.0      454.0   
3       NaN     NaN                  NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [17]:
pd.concat([df,df1],axis=1) # axis = 1 means columns,, axis = 0 then it is  rows

name  salary              mail_id addr  pf_nu  income_tax  mobile_no  \
0      sudh     100      sudh@ineuron.ai  blr    234         234      23543   
1     krish     200     krish@ineuron.ai  blr     45         565      43543   
2    hitesh     300    hitesh@ineuron.ai  blr  54465         767        454   
3  tuleshko     400  tuleshko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [18]:
data2 = {
    '0':['sudh','krish','hitesh','tuleshko'],
    '1':[100,200,300,400],
    '2' : ['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tuleshko@ineuron.ai'],
    '3':['blr','blr','blr','mum']
}
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [19]:
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

In [22]:
df2

0    1                    2    3
0      sudh  100      sudh@ineuron.ai  blr
1     krish  200     krish@ineuron.ai  blr
2    hitesh  300    hitesh@ineuron.ai  blr
3  tuleshko  400  tuleshko@ineuron.ai  mum

In [23]:
df3

0     1      2           3
0    234   234  23543          ds
1     45   565  43543     bigdata
2  54465   767    454    web dev 
3    656  6778   5656  blockchian

In [24]:
pd.concat([df2,df3]) # it will arrange in vertical columns due to same column name

0     1                    2           3
0      sudh   100      sudh@ineuron.ai         blr
1     krish   200     krish@ineuron.ai         blr
2    hitesh   300    hitesh@ineuron.ai         blr
3  tuleshko   400  tuleshko@ineuron.ai         mum
0       234   234                23543          ds
1        45   565                43543     bigdata
2     54465   767                  454    web dev 
3       656  6778                 5656  blockchian

In [25]:
data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

data5  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [26]:
df4 = pd.DataFrame(data4)
df5 = pd.DataFrame(data5)

In [27]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [28]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [29]:
pd.merge(df4,df5)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [30]:
pd.merge(df4,df5,how = 'left') # it is 1st copy data  from 1st table then fill data from 2nd table

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [31]:
pd.merge(df4,df5,how = 'right') # it is first second table then fill data from 1st table

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [32]:
pd.merge(df4,df5,how = 'inner') # it is by defoult inner merge

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [33]:
pd.merge(df4,df5,how = 'cross') # it will multipy one table with another 

emp_id_x  salary  pf  emp_id_y  mob_no  house_nu
0        101     234  23       101    3434       345
1        101     234  23       102    5656       345
2        101     234  23       104     767       345
3        101     234  23       105     878        56
4        102     345  34       101    3434       345
5        102     345  34       102    5656       345
6        102     345  34       104     767       345
7        102     345  34       105     878        56
8        103     200  56       101    3434       345
9        103     200  56       102    5656       345
10       103     200  56       104     767       345
11       103     200  56       105     878        56
12       104     400  78       101    3434       345
13       104     400  78       102    5656       345
14       104     400  78       104     767       345
15       104     400  78       105     878        56

In [34]:
pd.merge(df4,df5,on = 'emp_id')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [35]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

data7  = {'emp_id2' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [36]:
df6 = pd.DataFrame(data6)
df7 = pd.DataFrame(data7)

In [37]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [38]:
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [39]:
pd.merge(df6,df7) # No common columns to perform merge on

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [40]:
pd.merge(df6,df7, left_on='emp_id1',right_on='emp_id2') # used when column name are not same (for no key column)

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [41]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

data9  = {'emp_id' : [101,102,104,105,106],
          'salary' : [234, 345,200,400,500],
          'house_nu' : [345,345,345,56,45]
    
}

In [42]:
df8 = pd.DataFrame(data8)
df9 = pd.DataFrame(data9)

In [43]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [44]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     400        56
4     106     500        45

In [45]:
pd.merge(df8,df9, on = ['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [46]:
pd.merge(df8,df9) # by defoult it is act like above command 

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [47]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

data11  = {'emp_id2' : [101,102,104,105,106],
          'salary2' : [234, 345,200,400,500],
          'house_nu' : [345,345,345,56,45]
    
}

In [48]:
df10 = pd.DataFrame(data10, index=['a','b','c','d'])
df11 = pd.DataFrame(data11, index=['a','b','d','e','f'])

In [49]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [50]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      400        56
f      106      500        45

In [51]:
df10.join(df11) # it is match based on index

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [52]:
sale_data = pd.read_csv(r'C:\Users\LENOVO\Desktop\python codes\Pandas class\sales_data_final.csv')

In [53]:
sale_data

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage   
1      Oceania  ...  Office Supplies     Supplies   
2         EMEA  ...  Office Supplies      Storage   
3        North  ...  Office Supplies        Paper   
4      Oceania  ...        Furniture  Furnishings   
...        ...  ...              ...          ...   
51285     West  ...  Office Supplies      Binders   
51286   Africa  ...  Office Supplies      Binders   
51287  Central  ...  Office Supplies       Labels   
51288    North  ...  Office Supplies       Labels   
51289     West  ...  Office Supplies    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

       discount    profit  shipping_cost  order_priority  year  
0           0.0  106.1400          35.46          Medium  2011  
1           0.1   36.0360           9.72          Medium  2011  
2           0.0   29.6400           8.17            High  2011  
3           0.5  -26.0550           4.82            High  2011  
4           0.1   37.7700           4.70          Medium  2011  
...         ...       ...            ...             ...   ...  
51285       0.2    4.5188           0.89          Medium  2014  
51286       0.0    0.4200           0.49          Medium  2014  
51287       0.0   12.3600           0.35          Medium  2014  
51288       0.0    0.5600           0.20          Medium  2014  
51289       0.2   -0.6048           0.17   

In [54]:
def profit_flag(a):
    if a>0:
        return "Positive"
    else :
        return "Negative"
    

In [58]:
profit_flag(-10)

'Negative'

In [59]:
profit_flag(10)

'Positive'

In [60]:
sale_data['flag profit']=sale_data['profit'].apply(profit_flag)

In [61]:
sale_data.head(10)

order_id order_date ship_date       ship_mode     customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class   Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class     Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class      Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
5    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
6     CA-2011-1510   1/2/2011  1/6/2011  Standard Class   Magdelene Morse   
7    IN-2011-79397   1/3/2011  1/3/2011        Same Day       Kean Nguyen   
8    ID-2011-80230   1/3/2011  1/9/2011  Standard Class      Ken Lonsdale   
9     IZ-2011-4680   1/3/2011  1/7/2011  Standard Class  Lindsay Williams   

       segment            state      country  market   region  ...  \
0     Consumer      Constantine      Algeria  Africa   Africa  ...   
1     Consumer  New South Wales    Australia    APAC  Oceania  ...   
2     Consumer         Budapest      Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm       Sweden      EU    North  ...   
4     Consumer  New South Wales    Australia    APAC  Oceania  ...   
5     Consumer  New South Wales    Australia    APAC  Oceania  ...   
6     Consumer          Ontario       Canada  Canada   Canada  ...   
7    Corporate  New South Wales    Australia    APAC  Oceania  ...   
8     Consumer         Auckland  New Zealand    APAC  Oceania  ...   
9    Corporate           Ninawa         Iraq    EMEA     EMEA  ...   

                              product_name sales quantity discount   profit  \
0                      Tenex Lockers, Blue   408        2      0.0  106.140   
1                 Acme Trimmer, High Speed   120        3      0.1   36.036   
2                  Tenex Box, Single Width    66        4      0.0   29.640   
3              Enermax Note Cards, Premium    45        3      0.5  -26.055   
4               Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   
5  Eaton Computer Printout Paper, 8.5 x 11    55        2      0.1   15.342   
6                 Okidata Inkjet, Wireless   314        1      0.0    3.120   
7                  Hoover Microwave, White   276        1      0.1  110.412   
8              Hewlett Wireless Fax, Laser   912        4      0.4 -319.464   
9         Novimex Swivel Stool, Set of Two   667        4      0.0  253.320   

   shipping_cost  order_priority  year  flage profit flag profit  
0          35.46          Medium  2011      Positive    Positive  
1           9.72          Medium  2011      Positive    Positive  
2           8.17            High  2011      Positive    Positive  
3           4.82            High  2011      Negative    Negative  
4           4.70          Medium  2011      Positive    Positive  
5           1.80          Medium  2011      Positive    Positive  
6          24.10          Medium  2011      Positive    Positive  
7         125.32        Critical  2011      Positive    Positive  
8         107.10             Low  2011      Negative    Negative  
9          81.26            High  2011      Positive    Positive  

[10 rows x 23 columns]

In [66]:
sale_data.drop('flage profit',axis=1,inplace=True)

In [67]:
sale_data

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... sub_category  \
0       Africa  ...      Storage   
1      Oceania  ...     Supplies   
2         EMEA  ...      Storage   
3        North  ...        Paper   
4      Oceania  ...  Furnishings   
...        ...  ...          ...   
51285     West  ...      Binders   
51286   Africa  ...      Binders   
51287  Central  ...       Labels   
51288    North  ...       Labels   
51289     West  ...    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

      discount    profit  shipping_cost  order_priority  year flag profit  
0          0.0  106.1400          35.46          Medium  2011    Positive  
1          0.1   36.0360           9.72          Medium  2011    Positive  
2          0.0   29.6400           8.17            High  2011    Positive  
3          0.5  -26.0550           4.82            High  2011    Negative  
4          0.1   37.7700           4.70          Medium  2011    Positive  
...        ...       ...            ...             ...   ...         ...  
51285      0.2    4.5188           0.89          Medium  2014    Positive  
51286      0.0    0.4200           0.49          Medium  2014    Positive  
51287      0.0   12.3600           0.35          Medium  2014    Positive  
51288      0.0    0.5600           0.20          Medium  2014    Positive  
51289      0.2   -0.6048           0.17          Medium  2014    Negative  

[51290 rows x 22 columns]

In [68]:
sale_data['len of cust name']=sale_data['customer_name'].apply(len)

In [69]:
sale_data

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...                                     product_name sales  \
0       Africa  ...                              Tenex Lockers, Blue   408   
1      Oceania  ...                         Acme Trimmer, High Speed   120   
2         EMEA  ...                          Tenex Box, Single Width    66   
3        North  ...                      Enermax Note Cards, Premium    45   
4      Oceania  ...                       Eldon Light Bulb, Duo Pack   114   
...        ...  ...                                              ...   ...   
51285     West  ...  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14   
51286   Africa  ...          Wilson Jones Hole Reinforcements, Clear     4   
51287  Central  ...           Hon Color Coded Labels, 5000 Label Set    26   
51288    North  ...           Hon Legal Exhibit Labels, Alphabetical     7   
51289     West  ...                              Bagged Rubber Bands     3   

      quantity discount    profit  shipping_cost  order_priority  year  \
0            2      0.0  106.1400          35.46          Medium  2011   
1            3      0.1   36.0360           9.72          Medium  2011   
2            4      0.0   29.6400           8.17            High  2011   
3            3      0.5  -26.0550           4.82            High  2011   
4            5      0.1   37.7700           4.70          Medium  2011   
...        ...      ...       ...            ...             ...   ...   
51285        2      0.2    4.5188           0.89          Medium  2014   
51286        1      0.0    0.4200           0.49          Medium  2014   
51287        3      0.0   12.3600           0.35          Medium  2014   
51288        1      0.0    0.5600           0.20          Medium  2014   
51289        3      0.2   -0.6048           0.17          Medium  2014   

       flag profit len of cust name  
0         Positive               15  
1         Positive               11  
2         Positive               13  
3         Negative               12  
4         Positive               11  
...            ...              ...  
51285     Positive               10  
51286     Positive                9  
51287     Positive               16  
51288     Positive               13  
51289     Negative          

In [75]:
def quantity_flag(a):
    if a<5:
        return "LOW"
    elif a>5 and a<8:
        return "MEDIUM"
    else:
        return "HIGH"

In [76]:
sale_data['flag quantity']=sale_data['quantity'].apply(quantity_flag)

In [77]:
sale_data

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... sales quantity discount    profit shipping_cost  \
0       Africa  ...   408        2      0.0  106.1400         35.46   
1      Oceania  ...   120        3      0.1   36.0360          9.72   
2         EMEA  ...    66        4      0.0   29.6400          8.17   
3        North  ...    45        3      0.5  -26.0550          4.82   
4      Oceania  ...   114        5      0.1   37.7700          4.70   
...        ...  ...   ...      ...      ...       ...           ...   
51285     West  ...    14        2      0.2    4.5188          0.89   
51286   Africa  ...     4        1      0.0    0.4200          0.49   
51287  Central  ...    26        3      0.0   12.3600          0.35   
51288    North  ...     7        1      0.0    0.5600          0.20   
51289     West  ...     3        3      0.2   -0.6048          0.17   

       order_priority  year  flag profit  len of cust name flag quantity  
0              Medium  2011     Positive                15           LOW  
1              Medium  2011     Positive                11           LOW  
2                High  2011     Positive                13           LOW  
3                High  2011     Negative                12           LOW  
4              Medium  2011     Positive                11          HIGH  
...               ...   ...          ...               ...           ...  
51285          Medium  2014     Positive                10           LOW  
51286          Medium  2014     Positive                 9           LOW  
51287          Medium  2014     Positive                16           LOW  
51288          Medium  2014     Positive                13           LOW  
51289          Medium  2014     Negative                13           LOW  

[51290 rows x 24 columns]

In [78]:
sale_data['square_quantity']=sale_data['quantity'].apply(lambda a:a*a)

In [79]:
sale_data.head(5)

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag profit  \
0      0.0  106.140         35.46         Medium  2011     Positive   
1      0.1   36.036          9.72         Medium  2011     Positive   
2      0.0   29.640          8.17           High  2011     Positive   
3      0.5  -26.055          4.82           High  2011     Negative   
4      0.1   37.770          4.70         Medium  2011     Positive   

   len of cust name  flag quantity square_quantity  
0                15            LOW               4  
1                11            LOW               9  
2                13            LOW              16  
3                12            LOW               9  
4                11           HIGH              25  

[5 rows x 25 columns]

In [80]:
import numpy as np

In [81]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
type(np.array([1,2,3,4,5,6,7,8,9])) # n diamentional array

numpy.ndarray

In [84]:
np.array(([2,3,4],[5,6,4]))

array([[2, 3, 4],
       [5, 6, 4]])

In [88]:
np.array(([8,4,5,6],[7,9,6,3]))

array([[8, 4, 5, 6],
       [7, 9, 6, 3]])

In [85]:
l=[[1,2,3],[4,8,9]]

In [87]:
l[0][0]

1

In [93]:
a = np.array([3,4,5,6,7],ndmin = 3)

In [94]:
a

array([[[3, 4, 5, 6, 7]]])

In [95]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [96]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
arr.ndim  # it shows the diamensions of array

2

In [101]:
np.random.randint(1,10,(4,4)) # it generate the randon value in between 1 to 10, with 4 is to 4 diamension

array([[5, 4, 9, 8],
       [4, 8, 1, 6],
       [5, 2, 7, 2],
       [8, 4, 8, 9]])

In [102]:
np.random.randint(1,10,(4,4,2)) # 4X2 array and 4 times

array([[[9, 6],
        [1, 5],
        [8, 3],
        [1, 7]],

       [[4, 4],
        [1, 1],
        [1, 8],
        [3, 4]],

       [[3, 9],
        [7, 6],
        [3, 4],
        [2, 6]],

       [[5, 7],
        [5, 7],
        [9, 1],
        [5, 5]]])